apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers: 
        - name: my-app
          image: shashank9928/my-app:latest
          imagePullPolicy: IfNotPresent  
          ports:
           - containerPort: 80
      imagePullSecrets:
         - name: cicd-secret       
