---
- name: Install kubectl
  hosts: jenkins
  become: yes
  tasks:
    - name: Download kubectl binary
      get_url:
        url: https://dl.k8s.io/release/v1.27.1/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl

    - name: Ensure kubectl is executable
      command: chmod +x /usr/local/bin/kubectl

    - name: Ensure kubectl is installed
      command: kubectl version --client
      register: kubectl_version

    - name: Print kubectl version
      debug:
        msg: "kubectl version: {{ kubectl_version.stdout }}"
